name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        env:
          VULKAN_INCLUDE_PATH: /home/alexander/Vulkan/1.4.341.1/x86_64/include
          VULKAN_LIB_PATH: /home/alexander/Vulkan/1.4.341.1/x86_64/lib
          VULKAN_SPIRV_REFLECT_PATH: /home/alexander/Vulkan/1.4.341.1/x86_64/include
          VULKAN_BIN_PATH: /home/alexander/Vulkan/1.4.341.1/x86_64/bin
        run: cmake -S . -B Build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON

      - name: Build
        run: cmake --build Build --target Test -j$(nproc)

      - name: Test
        working-directory: Build
        env:
          LD_LIBRARY_PATH: Test/Build:Pengine/Build
        run: ctest --output-on-failure
