name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libvulkan-dev \
            libglfw3-dev \
            libshaderc-dev

      - name: Clone SPIRV-Reflect
        run: git clone --depth 1 https://github.com/KhronosGroup/SPIRV-Reflect.git /tmp/SPIRV-Reflect

      - name: Configure
        env:
          VULKAN_INCLUDE_PATH: /usr/include
          VULKAN_LIB_PATH: /usr/lib/x86_64-linux-gnu
          VULKAN_SPIRV_REFLECT_PATH: /tmp
          GLFW_INCLUDE_PATH: /usr/include
          GLFW_LIB_PATH: /usr/lib/x86_64-linux-gnu
        run: cmake -S . -B Build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON

      - name: Build
        run: cmake --build Build --target Test -j$(nproc)

      - name: Test
        working-directory: Build
        env:
          LD_LIBRARY_PATH: Test/Build:Pengine/Build
        run: ctest --output-on-failure
